export const countries = [
    { id: 1, name: "Argentina" },
    { id: 2, name: "Australia" },
    { id: 3, name: "Brazil" },
    { id: 4, name: "Canada" },
    { id: 5, name: "China" },
    { id: 6, name: "France" },
    { id: 7, name: "Germany" },
    { id: 8, name: "India" },
    { id: 9, name: "Italy" },
    { id: 10, name: "Japan" },
    { id: 11, name: "Mexico" },
    { id: 12, name: "Netherlands" },
    { id: 13, name: "Russia" },
    { id: 14, name: "South Africa" },
    { id: 15, name: "South Korea" },
    { id: 16, name: "Spain" },
    { id: 17, name: "Sweden" },
    { id: 18, name: "Switzerland" },
    { id: 19, name: "Turkey" },
    { id: 20, name: "United Kingdom" },
    { id: 21, name: "United States" },
    { id: 22, name: "Afghanistan" },
    { id: 23, name: "Austria" },
    { id: 24, name: "Belgium" },
    { id: 25, name: "Chile" },
    { id: 26, name: "Colombia" },
    { id: 27, name: "Denmark" },
    { id: 28, name: "Egypt" },
    { id: 29, name: "Finland" },
    { id: 30, name: "Greece" },
    { id: 31, name: "España" }
  ];
  
  
  